apiVersion: v1
kind: Service
metadata:
  name: {{ include "mergestat.fullname" . }}-graphql
spec:
  selector:
    mergestat-component: graphql
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5433
