apiVersion: v1
kind: Service
metadata:
  name: {{ include "mergestat.fullname" . }}-ui
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    mergestat-component: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
