apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuse.fullname" . }}-ui
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "fuse.selectorLabels" . | nindent 6 }}
      fuse-component: ui
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuse.selectorLabels" . | nindent 8 }}
        fuse-component: ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          # TODO(patrickdevivo) the /repos path will need to get amended when we ship auth
          # will probably want an explicit /healthz endpoint or similar (in the UI code)
          livenessProbe:
            httpGet:
              path: /repos
              port: 3000
          readinessProbe:
            httpGet:
              path: /repos
              port: 3000
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            {{- if .Values.ui.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.ui.env "context" $ ) | nindent 12 }}
            {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
