apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuse.fullname" . }}-ui
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    fuse-component: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
