apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuse.fullname" . }}-ui
   {{- with .Values.ui.service.annotations }}
    annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    fuse-component: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
