{{- if .Values.worker.pvc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mergestat.fullname" . }}-worker-pvc
  {{- with .Values.worker.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mergestat.labels" . | nindent 4 }}
spec:
{{- if .Values.worker.pvc.storageClass }}
  storageClassName: {{ .Values.worker.pvc.storageClass }}
{{- end }}
  accessModes:
    - {{ .Values.worker.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.worker.pvc.size }}
{{- end }}
